### PR TITLE
Add docker input to WDL, remove zones

### PR DESCRIPTION
**Pull request by ruchim**
This makes the workflow such that the options file is no longer required to run.

### CODE REVIEW

**Comment by ruchim** [comment]
@eitanbanks - would you mind reviewing these changes that remove the workflow options file? This change is meant to make the workflow source files Dockstore compatible. Thanks!

**Comment by eitanbanks** [comment]
Everything looks reasonable.
I see that the inputs file is being removed.  Do we store the inputs somewhere else now?

**Comment by ruchim** [comment]
The inputs file was renamed, and never added the new file to my commit. Thanks for catching that Eric, its now fixed. Can @wshands or @briandoconnor help merge this? Thanks!

**Comment by wshands** [comment]
Hi Ruchi,
Is the zones attribute not needed? I notice it was in the .options file but I don't see it in the updated WDL

**Comment by ruchim** [comment]
Hey Walt,

There are default zones already being applied to all workflows running against a Google backend, so its not a true requirement. When running lots of jobs, one can start depleting resources from the default zones, and thus this option allows the jobs to spread across more zones/regions to reduce the bottleneck on compute resources.

**Comment by wshands** [comment]
This looks OK to me, but there are conflicts that must be resolved...Ruchi?

**Comment by wshands** [comment]
@ruchim would you please fix the conflicts so we can merge this branch?

**Pull request merged**
