### PR TITLE
Changed steps in order to work locally.

### PR DESCRIPTION
**Pull request by vladimir-obucina**
There was some code needed for our platform, that was changing command line in cwltool, which is now removed.

### CODE REVIEW

**Review by wshands — CHANGES_REQUESTED** [review]
Hi,
Looks OK except please leave the Google cloud storage paths in the JSON file so others know a place they can find the files.

**Comment by vladimir-obucina** [comment]
Hi Walt,

I've made those changes. Have you tried running the workflow?

**Comment by wshands** [comment]
It is running now

**Review by wshands — APPROVED** [review]
Looks OK to me

**Pull request merged**
