### PR TITLE
Changed cwl workflows and input jsons 

### PR DESCRIPTION
**Pull request by vladimir-obucina**
Changed cwl workflows and input jsons so they are now similar to those in wdl, and paths inside json are from cloud storage, so hopefully now can be run with those files while testing. There are also checker workflow and concordance workflow. Checker is working, concordance testing still needs to be modified.

### CODE REVIEW

**Comment by wshands** [comment]
Vlada, should we wait for the concordance checker before merging?

**Comment by vladimir-obucina** [comment]
Hi Walt,

I think you can merge, and when I'm done with concordance checker, I'll
make another pull request. It worked, but since I made few modifications to
the main workflow it needs some changes. Is it urgent or?

Best,

Vlada

**Comment by wshands** [comment]
If you will be finished with the changes to the concordance checker today or early I will wait to make a release. I would like to release with the complete variant caller and variant caller checker workflows.  Thanks!

**Comment by wshands** [comment]
Vlada would you please make the pull request to the develop branch instead of the master branch?

**Comment by vladimir-obucina** [comment]
Hey Walt, I've tried to change the pull request to develop branch, but it says: A pull request already exists for base branch 'develop' and head branch 'variant-calling-cwl'.

There is another pull request after this one, which is to develop branch, so maybe I should just delete this pull request, and you could then merge that one.

**Comment by wshands** [comment]
OK if all the changes are in the other pull request then delete this one and I will merge the other one

**Pull request closed without merging**
