### PR TITLE
Variant calling cwl concordance update

### PR DESCRIPTION
**Pull request by vladimir-obucina**
Removed validation test files, which are not needed anymore, and concordance test now works on our platform.

### CODE REVIEW

**Comment by wshands** [comment]
I could not figure out where ConcordanceCheckerWorkflow is called; it seems like it should be called from one of the CWL files...

**Comment by vladimir-obucina** [comment]
There is separate folder inside Variant Caller Checker folder for CWL Concordance Checker workflow, which consists of two tools - GATK Concordance and GATK Concordance Checker, it can be run from there, it just requires inputs to be given. I've done it the same way like here: https://github.com/DataBiosphere/topmed-workflows/tree/master/vcf-comparator . Should it be like that, or should I connect it to the main Variant Calling workflow?

**Comment by wshands** [comment]
OK let me know when to merge this; I suppose after you delete the other pull request?

**Comment by wshands** [comment]
OK to merge now?

**Comment by vladimir-obucina** [comment]
yes, sorry for the delay

**Pull request merged**
