### PR TITLE
FunctionalEquivalence WDL workflow

### PR DESCRIPTION
**Pull request by ruchim**

### CODE REVIEW

**Comment by ruchim** [comment]
It'd be great to have @eitanbanks review it once prior to merging.

**Comment by eitanbanks** [comment]
Looks great to me!

**Comment by ruchim** [comment]
@briandoconnor @wshands Would someone mind merging this when they get a chance? Thanks!

**Comment by wshands** [comment]
@briandoconnor would you please merge this?

**Pull request merged**
